export const USER_SIGN_UP = 'USR_SIGNUP';
export type USER_SIGN_UP = typeof USER_SIGN_UP;

export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export type SIGN_UP_ERROR = typeof SIGN_UP_ERROR;

export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export type SIGN_IN_ERROR = typeof SIGN_IN_ERROR;

export const USER_SIGN_IN = 'USER_SIGN_IN';
export type USER_SIGN_IN = typeof USER_SIGN_IN;

export const SIGN_IN_SUCCES = 'SIGN_IN_SUCCES';
export type SIGN_IN_SUCCES = typeof SIGN_IN_SUCCES;

export const SIGN_UP_SUCCES = 'SIGN_UP_SUCCES';
export type SIGN_UP_SUCCES = typeof SIGN_UP_SUCCES;

export const USER_CONFIRMATION = 'USER_CONFIRMATION';
export type USER_CONFIRMATION = typeof USER_CONFIRMATION;

export const APP_CONNECTION_ERROR = 'APP_CONNECTION_ERROR';
export type APP_CONNECTION_ERROR = typeof APP_CONNECTION_ERROR;

export const STREAM_CONN_ERROR = 'STREAM_CONN_ERROR';
export type STREAM_CONN_ERROR = typeof STREAM_CONN_ERROR;

export const USER_CONFIRMATION_ERROR = 'USER_CONFIRMATION_ERROR';
export type USER_CONFIRMATION_ERROR = typeof USER_CONFIRMATION_ERROR;

export const USER_LOG_OUT = 'USER_LOG_OUT';
export type USER_LOG_OUT = typeof USER_LOG_OUT;

// fix name

export const CONNECTION_TO_STREAM = 'CONNECTION_TO_STREAM';
export type CONNECTION_TO_STREAM = typeof CONNECTION_TO_STREAM;

export const LEAVING_STREAM = 'LEAVING_STREAM';
export type LEAVING_STREAM = typeof LEAVING_STREAM;

export const CHAT_MESSAGE_EMMITION = 'CHAT_MESSAGE_EMMITION';
export type CHAT_MESSAGE_EMMITION = typeof CHAT_MESSAGE_EMMITION;

export const CLEAR_CHAT = 'CLEAR_CHAT';
export type CLEAR_CHAT = typeof CLEAR_CHAT;

export const START_STREAM = 'START_STREAM';
export type START_STREAM = typeof START_STREAM;

export const STOP_STREAM = 'STOP_STREAM';
export type STOP_STREAM = typeof STOP_STREAM;

export const APP_LOAD_CHANNELS = 'APP_LOAD_CHANNELS';
export type APP_LOAD_CHANNELS = typeof APP_LOAD_CHANNELS;

export const APP_LOAD_MORE_CHANNELS = 'APP_LOAD_MORE_CHANNELS';
export type APP_LOAD_MORE_CHANNELS = typeof APP_LOAD_MORE_CHANNELS;

export const APP_CLEAR_LOADED_CHANNELS = 'APP_CLEAR_LOADED_CHANNELS';
export type APP_CLEAR_LOADED_CHANNELS = typeof APP_CLEAR_LOADED_CHANNELS;

export const APP_REFRESH_CHANNELS_LIST = 'APP_REFRESH_CHANNELS_LIST';
export type APP_REFRESH_CHANNELS_LIST = typeof APP_REFRESH_CHANNELS_LIST;

export const APP_CLEAR_CHANNELS_DATA = 'APP_CLEAR_CHANNELS_DATA';
export type APP_CLEAR_CHANNELS_DATA = typeof APP_CLEAR_CHANNELS_DATA;

export const APP_SET_USER_DATA = 'APP_SET_USER_DATA';
export type APP_SET_USER_DATA = typeof APP_SET_USER_DATA;
